config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :club_groups do
     resources :posts
     member do
         post :join
         post :quit
     end
  end

  namespace :account do
     resources :club_groups
     resources :posts
  end

  namespace :admin do 
     resources :events

  end

  resources :events do 
     collection do
        get :search
     end
     member do
        get :dashboard
     end
     resources :attendees , :controller => 'event_attendees'
     resource :location , :controller => 'event_locations'
     resource :state , :controller => 'event_states'
  end

   

end

app/models/event.rb
#encoding:utf-8
class Event < ActiveRecord::Base
   validates_presence_of :name
   has_one :location
   has_many :attendees
   has_many :questions , :dependent => :destroy
   belongs_to :category
   has_many :event_groupships
   has_many :groups , :through => :event_groupships
   delegate :name, :to => :category , :prefix => true , :allow_nil => true
   accepts_nested_attributes_for :questions , :reject_if => lambda { |a| a[:content].blank?  } , :allow_destroy => true
   accepts_nested_attributes_for :location , :allow_destroy => true , :reject_if => :all_blank

   #def category_name
   #   self.category.nil? ? "沒有所屬的類別" : self.category.name 
   #end
   
   alias category_name_old category_name
   def category_name
      old = category_name_old
      old.nil? ? "沒有設定Category" : old
   end

   def closed?
      self.status == "CLOSED"
   end

   def open?
      !self.closed?
   end

   def open!
      self.status = "OPEN"
      self.save!
   end

   def close!
      self.status = "CLOSED"
      self.save!
   end


end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
   before_filter :authenticate
   layout "admin"

   def index

   end

   protected

   def authenticate
      @user_name = "N/A"
      authenticate_or_request_with_http_basic do |user_name,password|
         @user_name = user_name
         user_name == 'admin' && password == 'admin'
      end
   end


end

app/controllers/events_controller.rb
#encoding:utf-8
class EventsController < ApplicationController
   
   before_filter :find_event , :only => [:show,:edit,:update,:destroy]
   
   
   # 進入主網頁時，讀取所有資料
   def index
      sort_by = (params[:order] == 'name') ? 'name' : 'created_at'
      @events = Event.order(sort_by).page(params[:page]).per(5)

      respond_to do |format|
         #debugger
         format.html # index.html.erb
         format.xml { render :xml => @events.to_xml }
         format.json { render :json => @events.to_json }
         format.atom { @feed_title = "My event list"} # index.atom.builder
      
      end

   end
   # 新增資料的處理
   def new
      @event = Event.new
      @groups = Group.all
      3.times do 
         question = @event.questions.build 
         4.times do 
            question.answers.build
         end
      end
   end
   # 處理創立資料
   def create
      @event = Event.new(new_params)
      @groups = Group.all
      if @event.save
         redirect_to events_url
         flash[:notice] = "event was successfully created"
      else
         render :action => 'new'
      end

   end
   # 顯示個別資料 
   def show
      @groups = Group.all
      respond_to do |format|
         format.html {@page_title = "showing:#{@event.name}"}
         format.xml # show.xml.builder
         format.json {render :json => { id: @event.id , name: @event.name }.to_json }
      end
   end
   # 編輯資料 
   def edit
      @groups = Group.all
   end
   # 更新資料
   def update
      if @event.update(new_params)
         redirect_to event_url(@event)
         flash[:notice] = "update successfully!"
      else
         render :action => :edit
      end
   end
   # 刪除資料
   def destroy
      @event.destroy
      flash[:alert] = "delete successfully!"
      redirect_to events_url
   end


   def search
      @events = Event.where( 
                              ["name like ?","%#{params[:keyword]}%"]
                           ).page(params[:page] ).per(5)
      render :action => :index
   end

   def dashboard
      @event = Event.find(params[:id])
   end

   protected
   
   # 尋找事件
   def find_event
      @event = Event.find(params[:id])
   end

   # 新進資料先行處理
   def new_params
      params.require(:event).permit(:name,:description,:category_id, :group_ids => [], :location_attributes => [:id , :name , :event_id , :_destroy] ,:questions_attributes => [:id,:event_id,:content,:_destroy , :answers_attributes =>[ :id , :question_id , :content  , :_destroy] ])
   end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
   def category_options
      Category.all.collect do |c|
         [c.name , c.id]
      end
   end

   def setup_event(event)
      event.build_location unless event.location
      event
   end

end

app/views/events/_answer_fields.html.erb
<p class="fields">
   <%= f.label :content , "答案：" %>
   <%= f.text_field :content %>
   <%= link_to_remove_fields("刪除此答案",f) %>
</p>

app/views/events/_form.html.erb
<%= f.label :name, "Name" %>
<%= f.text_field :name %>
<%= f.label :description, "Description" %>
<%= f.text_area :description %>
<%= f.select :category_id , category_options %><br />

<%- "這裡是處理location" %>
<%= f.fields_for :location do |location_form| %>
   <p>
   <%= location_form.label :name , "地點名稱" %>
   <%= location_form.text_field :name %>
   
   <% unless location_form.object.new_record? %>
      <%= location_form.label :_destroy , "移除地點" %>
      <%= location_form.check_box :_destroy %>
   <% end %>
   </p>
<% end %>

<%- "處理群組" %>
<% @groups.each do |g| %>
   <%= check_box_tag("event[group_ids][]",g.id,@event.groups.map(&:id).include?(g.id)) %><%= g.name %><br />
<% end %>

<%= hidden_field_tag 'event[group_ids][]','' %>



<%= f.fields_for :questions do |builder| %>
   <%= render  'question_fields' ,  :f => builder  %> 
<% end %>
<p><%= link_to_add_fields("新增問題",f,:questions) %></p>

<% if @event.errors.any? %>
   <ul>
   <% @event.errors.full_messages.each do |msg| %>
         <li> <%= msg %></li>
   <% end %>
   </ul>
<% end %>

app/views/events/_question_fields.html.erb
<div class="fields">
   <p>
   <%= link_to_remove_fields("移除此問題",f) %>
      <%= f.label :content,"問題欄位" %><br />
      <%= f.text_area :content, :row => 2 %><br />
   </p>
   <%= f.fields_for :answers do |builder| %>
      <%= render 'answer_fields' , :f => builder %>
   <% end %>
   <p><%= link_to_add_fields("新增答案",f,:answers) %></p>
</div>

app/views/events/dashboard.html.erb
<h1><%= "Wekcome to #{@event.name}'s Dashboard！" %></h1>
<p>這裡是其他的額外頁面，但是目前還沒有定案...<p>

app/views/events/edit.html.erb
<%= form_for setup_event(@event), :url => event_path(@event), :method => :put do |f| %>
   <%= render :partial => 'form' , :locals => {:f => f} %>

   <%= f.submit "更新！" %>
<% end %>

app/views/events/index.html.erb
<%= form_tag search_events_path, :method => :get do %>
   關鍵字：<%= text_field_tag "keyword" , nil ,:placeholder => "Search Event name..."  %>
   <%= submit_tag "Search" %>
<% end %>
<%= link_to 'Sort by name' , events_path(:order =>'name') %>
<%= link_to 'Sort by default' , events_path %>

<%- # 時間統計 %>
<% benchmark("Rendering Page Event") do %>

<ul>
<% @events.each do |event| %>
   <li>
   <%= "Event name:" %>
   <%= link_to event.name, event_path(event) %><br />
   <%= link_to 'View Dashboard' , dashboard_event_path(event) %><br />
   <%= link_to 'View XML', event_path(event  , :format => :xml ) %><br />
   <%= link_to 'View JSON', event_path(event  ,:format => :json) %><br />
   <%= link_to 'View attendee', event_attendees_path(event) %><br />
   <%= link_to 'View location' , event_location_path(event) %><br />
   <div style="float:left;width:50px;">
   <%= button_to 'Edit',edit_event_path(event), :method => :get , :class => "btn btn-primary btn-sm" , :form => {:style => "display:inline;margin:0;padding:0;"}  %>
</div> 
   <%= button_to 'Delete',event_path(event) , :method => :delete  , :class => "btn btn-primary btn-sm" , :form => {:style=>"display:inline;"}  %>
</div>
   </li>
<% end %>
</ul>
<%= button_to 'New event', new_event_path , :method => :get  %>
<%= paginate @events %>

<%  end #結束時間統計 %>

app/views/events/new.html.erb
<%= form_for setup_event(@event) , :url => events_path do |f|  %>
   <%= render :partial => 'form', :locals => { :f => f}  %>
      
   <%= f.submit "Create" %>
<% end %>

app/views/events/show.html.erb
<%= @event.name %>
<p>狀態： <%= @event.status %></p>
<p>
<% if @event.closed? %>
   <%= link_to '[Open]' , event_state_path(@event) , :method => :post %>
<% else %>
   <%= link_to '[Close]' , event_state_path(@event) , :method => :delete %>
<% end %>
</p>


<%= simple_format(@event.description) %>
<p>Category:<%= @event.category_name %></p>
<% @event.questions.each_with_index do |q,index| %>
   <%= simple_format("Question #{index+1}：" + q.content) %>
   <ul>
      <% q.answers.each do |ans| %>
         <li>
            <%=  ans.content %>
         </li>
      <% end %>
   </ul>
<% end %>
<%= debug(@event) %>
<% Rails.logger.debug("DEBUG:event: #{@event.inspect}") %>
<p><%= link_to 'Back to index', events_path %>