config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :club_groups do
     resources :posts
     member do
         post :join
         post :quit
     end
  end

  namespace :account do
     resources :club_groups
     resources :posts
  end

  namespace :admin do 
     resources :events

  end

  resources :events do 
     collection do
        get :search
     end
     member do
        get :dashboard
     end
     resources :attendees , :controller => 'event_attendees'
     resource :location , :controller => 'event_locations'
     resource :state , :controller => 'event_states'
  end

   

end

app/models/club_group.rb
class ClubGroup < ActiveRecord::Base
   validates :title, :presence => true
   has_many :posts 
   has_many :group_userships
   has_many :members , :through => :group_userships , :source => :user
   belongs_to :owner , :class_name => "User" , :foreign_key => :user_id
   after_create :join_owner_to_group

   def editable_by?(user)
      user && user == owner
   end

   def join_owner_to_group
      members << owner
   end


end

app/controllers/account/club_groups_controller.rb
class Account::ClubGroupsController < ApplicationController
   before_action :login_required

   def index
      @groups = current_user.participated_groups

   end

   

end

app/controllers/club_groups_controller.rb
class ClubGroupsController < ApplicationController
   before_filter :find_group , :only => [:edit,:update,:destroy]
   before_action :login_required, :only => [:new , :create , :edit , :update , :destroy]


   # Index
   def index
      @groups = ClubGroup.all
   end

   # Show
   def show
      @group = ClubGroup.find(params[:id])
      @posts = @group.posts.order("updated_at DESC")
   end

   # New
   def new
      @group = ClubGroup.new
   end
   
   # Create
   def create
      @group = current_user.club_groups.build(group_params)
      if @group.save
         redirect_to club_groups_path
      else
         render :action => :new
      end
   end

   def edit
   end

   def update 
      if @group.update(group_params)
         redirect_to club_groups_path
      else
         render :action => :edit
      end
   end

   def destroy
      @group.destroy
      redirect_to club_groups_path
   end


   def join
      @group = ClubGroup.find(params[:id])
      if !current_user.is_member_of?(@group)
         current_user.join!(@group)
      else
         flash[:alert] = "You already joined this group."
      end
      redirect_to club_group_path(@group)

   end

   def quit
      @group = ClubGroup.find(params[:id])
      if current_user.is_member_of?(@group)
         current_user.quit!(@group)
      else
         flash[:alert] = "You are not member of this group"
      end
      redirect_to club_group_path(@group)

   end


   protected
   # before_filter：找到group
   def find_group
      @group = current_user.club_groups.find(params[:id])
   end
   # 經過permit的mass參數 
   def group_params(extra_allow = [])
     params.require(:club_group).permit([:title , :description] + extra_allow)
   end


end

app/helpers/account/club_groups_helper.rb
module Account::ClubGroupsHelper
end

app/helpers/club_groups_helper.rb
module ClubGroupsHelper
end

app/views/club_groups/_group_form.html.erb
<%= f.label :title , "Title" %><br />
<%= f.text_field :title , :class => "input-xxlarge" %><br />
<%= f.label :description , "Description" %><br />
<%= f.text_area :description ,:class => "input-xxlarge"  %>

<div class="form-actions">
   <%= f.submit "Submit" ,:disable_with => "Submiting..." , :class => "btn btn-primary"  %>
</div>

app/views/club_groups/edit.html.erb
<div class="span12">

<%= form_for @group , :url => club_group_path(@group) do |f|  %>
   <%= render "group_form",:f => f  %>
<% end %>
</div>

app/views/club_groups/index.html.erb
<div class="account" >
   <%= link_to "Sign up" , new_user_registration_path , :class => "btn btn-primary" %>
   <%= link_to "Login" , new_user_session_path , :class => "btn btn-warning"   %>
   <%==link_to "Logout" , destroy_user_session_path , :method => :delete ,  :class => "btn btn-danger"  %>

</div>

<div class="span12">
   <div class="group">
      <%= link_to "New Group", new_club_group_path , :class => "btn btn-mini btn-primary pull-right" %>
   </div>
   <table class="table">
      <thead>
         <tr>
            <td> # </td>
            <td> Title </td>
            <td> Description </td>
            <td> Owner </td>
         </tr>
      </thead>
      <tbody>
         <% @groups.each do |group| %>
         <tr>
            <td> # </td>
            <td> <%= link_to(truncate(group.title , :length => 17),club_group_path(group)) %> </td>
            <td><%= group.description %></td>
            <td><%= group.owner.name %></td>

            <% if current_user && group.editable_by?(current_user) %>
               <td> <%= link_to("Edit",edit_club_group_path(group) , :class => "btn btn-mini")  %>
               <td> <%= link_to "Delete", club_group_path(group) , :class => "btn btn-mini" , :method => "delete" , :confirm => "Are you sure?" %> </td>
            <% end %>

         </tr>
         <% end %>
      </tbody>
   </table>

app/views/club_groups/new.html.erb
<div class="span12">

<%= form_for @group , :url => club_groups_path do |f|  %>
   <%= render "group_form",:f => f  %>
<% end %>
</div>

app/views/club_groups/show.html.erb
<div class="span12">
   <div class="group">
      <%- # 群組控制  %>
      <% if current_user %>
         <div class="group">
         <% if current_user.is_member_of?(@group) %>
            <%= link_to "Quit Group" , quit_club_group_path(@group),:method => :post , :class => "btn btn-mini btn-warning" %>
         <% else %>
            <%= link_to "Join Group" , join_club_group_path(@group) , :method => :post , :class => "btn -btn-mini btn-primary" %>
         <% end %>
         </div>
      <br />
      <% end %>
      <%- # 文章控制 %>
      <% if current_user %>
         <% if current_user.is_member_of?(@group) %>
            <%= link_to "New Post",new_club_group_post_path(@group) , :class => "btn btn-mini btn-danger"  %>
         <% end %>
         <% if @group.editable_by?(current_user) %>
               <%= link_to "Edit" , edit_club_group_path(@group) , :class => "btn btn-mini btn-primary pull-right" %>
         <% end %>
         <%= link_to "Back to Index" , club_groups_path , :class => "btn btn-mini btn-warning pull-right" %>
      <% end %>
   </div>

   <h2> <%= @group.title %> </h2>
   
   <p> <%= @group.description %> </p>

   <table class="table">
      <tbody>
      <% @posts.each do |post| %>
         <tr>
            <td>
               <span class="author">
                  <strong>Author: <%= post.author.name %></strong>
               </span>
               <p>
                  <%= simple_format(post.content) %>
               </p>
            </td>
            <% if current_user && post.editable_by?(current_user) %>
               <td><%= link_to "Edit", edit_club_group_post_path(post.club_group,post) , :class => "btn btn-mini" %></td>
               <td><%= link_to "Delete", club_group_post_path(post.club_group,post) , :class => "btn btn-mini" , :method => :delete , :confirm => "Are you sure?" %></td>
            <% end %>

         </tr>
      <% end %>
      </tbody>
   </table>


</div>