config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :club_groups do
     resources :posts
     member do
         post :join
         post :quit
     end
  end

  namespace :account do
     resources :club_groups
     resources :posts
  end

  namespace :admin do 
     resources :events

  end

  resources :events do 
     collection do
        get :search
     end
     member do
        get :dashboard
     end
     resources :attendees , :controller => 'event_attendees'
     resource :location , :controller => 'event_locations'
     resource :state , :controller => 'event_states'
  end

   

end

app/models/post.rb
class Post < ActiveRecord::Base
   belongs_to :club_group , :foreign_key => :club_group_id , :counter_cache => true
   belongs_to :author , :class_name => "User" , :foreign_key => :user_id
   validates :content , :presence => true
   scope :recent , -> {order("updated_at DESC")}

   def editable_by?(user)
      user && user == author
   end

end

app/controllers/account/posts_controller.rb
class Account::PostsController < ApplicationController
   def index
      @posts = current_user.posts.recent
   end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   before_filter :find_group 
   before_filter :find_post , :only => [:edit,:update,:destroy]
   before_action :login_required , :only => [:new , :create , :edit , :update , :destroy]
   before_action :member_required , :only => [:new , :create]

   def edit
      @page_title = "Edit Post"
   end

   def update
      if @post.update(post_params)
         redirect_to club_group_path(@group)
      else
         render :action => :edit
      end

   end

   def destroy
      @post.destroy
      redirect_to club_group_path(@group)
   end

   def new
      @page_title = "New PoST"
      @post = @group.posts.build
   end

   def create
      @post = @group.posts.new(post_params)
      @post.author = current_user
      if @post.save
         redirect_to club_group_path(@group)
      else
         render :new
      end
   end

   protected
   def find_group
      @group = ClubGroup.find(params[:club_group_id])
   end

   def find_post
      @post = current_user.posts.find(params[:id])
   end

   def post_params(extra_allow=[])
      params.require(:post).permit([:content,:club_group_id] + extra_allow)
   end

   def member_required
      if !current_user.is_member_of?(@group)
         flash[:alert] = "You are not member of this group!"
         redirect_to club_group_path(@group)
      end
   end

end

app/helpers/account/posts_helper.rb
module Account::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post_form.html.erb
<%= f.text_area :content %>
<div class="form-actions">
   <%= f.submit "Submit" , :disable_with => "Submiting..." , :class => "btn btn-primary" %>
</div>
<% if @post.errors.any?  %>
   <ul>
   <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
   <% end %>
   </ul>
<% end %>

app/views/posts/edit.html.erb
<p><%= "Edit Post in #{@group.title}" %></p>
<div class="span12">
<%= form_for @post ,:url => club_group_post_path(@group,@post) do |f| %>
   <%= render "post_form" , :f => f %>
<% end %>
</div>

app/views/posts/new.html.erb
<p<%= "New Post for #{@group.title}" %></p>
<div class="span12">
<%= form_for @post ,:url => club_group_posts_path(@group) do |f| %>
   <%= render "post_form" , :f => f %>
<% end %>
</div>